# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MyDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyDemo

  pod 'LXYModularTool', '~> 0.0.1'


  target 'MyDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
